/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasmateri_3;

/**
 *
 * @author TUAN MUDA PULANGMAGANG
 */
import static com.sun.java.accessibility.util.AWTEventMonitor.addActionListener;
import java.applet.Applet;
import java.awt.Button;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class tugasmateri_3c extends java.applet.Applet implements ActionListener{
TextField input1, input2;
  Button tambah, kurang, kali;
  Label hasilp, Label1, Label2;
  int a, b, hsl;
    
    public void init() {
    Label input1Label = new Label (" ",Label.RIGHT);
    Label input2Label = new Label (" ",Label.RIGHT);
    
        input1 = new TextField(12);
        input2 = new TextField(12);
        tambah = new Button ("Tambah");
        kurang = new Button ("Kurang");
        kali = new Button ("Kali");
    
    add(input1Label);
    add(input1);
   
    add(input2Label);
    add(input2);
     
    add (tambah);
    tambah.addActionListener(this);
    
    add (kurang);
    kurang.addActionListener(this);
    
    add (kali);
    kali.addActionListener(this);    
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
