/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasmateri_3;
import java.applet.Applet;
import java.awt.Button;
import java.awt.Graphics;
import java.awt.Label;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author TUAN MUDA PULANGMAGANG
 */
public class tugasmateri_3a extends Applet implements ActionListener {
    
    TextField input, output;
    Button krm;
    
    @Override
    public void init() {
    Label  inputLabel= new Label (" ",Label.RIGHT);
    Label  outputLabel= new Label (" ",Label.RIGHT);
        
    input = new TextField(15);
    output = new TextField(15);
    krm = new Button ("Kirim");
        
    add(inputLabel);
    add(input);
   
    add(outputLabel);
    add(output);
     
    add (krm);
    krm.addActionListener(this);
    }
    @Override
    public void actionPerformed(ActionEvent ae){
    repaint();
    }
    @Override
    public void paint (Graphics g){

    krm.setLocation(40,50);
    output.setLocation(40,90);
     
        output.setText(input.getText());
    }


    /**
     * Initializes the applet materi_31
     */
                    



    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    
    // </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   



    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
